# Generated by Django 4.1.7 on 2023-03-20 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='monthWiseAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountNumber', models.BigIntegerField()),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('analysis', models.TextField()),
            ],
        ),
    ]
