# Generated by Django 4.1.7 on 2023-03-20 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthwiseanalytics',
            name='phoneNumber',
            field=models.BigIntegerField(default=12345678),
            preserve_default=False,
        ),
    ]
