# Generated by Django 4.1.7 on 2023-03-21 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_monthwiseanalytics_analysis_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthwiseanalytics',
            name='avgBalance',
        ),
        migrations.RemoveField(
            model_name='monthwiseanalytics',
            name='avgSpending',
        ),
        migrations.RemoveField(
            model_name='monthwiseanalytics',
            name='largeCreditSources',
        ),
        migrations.RemoveField(
            model_name='monthwiseanalytics',
            name='largeDebitSources',
        ),
        migrations.RemoveField(
            model_name='monthwiseanalytics',
            name='monthlyLoan',
        ),
        migrations.RemoveField(
            model_name='monthwiseanalytics',
            name='spendingIncomeRatio',
        ),
    ]
