# Generated by Django 4.1.7 on 2023-03-21 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_monthwiseanalytics_avgbalance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthwiseanalytics',
            name='averageDayWiseExpense',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monthwiseanalytics',
            name='averageDayWiseIncome',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monthwiseanalytics',
            name='categorizedData',
            field=models.JSONField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monthwiseanalytics',
            name='creditDebitFrequency',
            field=models.JSONField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monthwiseanalytics',
            name='loanDetails',
            field=models.JSONField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monthwiseanalytics',
            name='spendingExpenseRatio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monthwiseanalytics',
            name='totalMonthExpense',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monthwiseanalytics',
            name='totalMonthIncome',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monthwiseanalytics',
            name='transactionTypes',
            field=models.JSONField(default=0),
            preserve_default=False,
        ),
    ]
