# Generated by Django 4.1.7 on 2023-03-21 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_monthwiseanalytics_averagedaywiseexpense_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthwiseanalytics',
            name='phoneNumber',
        ),
    ]
