# Generated by Django 4.1.7 on 2023-03-24 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_monthwiseanalytics_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthwiseanalytics',
            name='rtgsData',
            field=models.JSONField(default={'data': 'No data'}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monthwiseanalytics',
            name='taxedData',
            field=models.JSONField(default={'data': 'No data'}),
            preserve_default=False,
        ),
    ]
